export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
export const REMOVE_SEARCH_RESULTS = 'REMOVE_SEARCH_RESULTS'
export const SET_LOADING = 'SET_LOADING'
export const REMOVE_LOADING = 'REMOVE_LOADING'
